### ISSUE TITLE
Burze.dzis.net - Integration not available

### ISSUE THREAD

**Issue by senderbell** [MrBartusek/MeteoalarmCard#248] opened 2024-03-24 11:21 UTC
### Describe the bug

When I try to add a card to the dashboard, I receive a message that the integration "burze.dzis.net" is not available. The integration itself works fine, all sensors are accessible.

### Integration state attributes

attribution: Information provided by Burze.dzis.net.
device_class: safety
icon: mdi:weather-lightning-rainy
friendly_name: Burze.dzis.net Ostrzezenie - Burza

### Screenshots

![Obszar ekranu](https://github.com/MrBartusek/MeteoalarmCard/assets/120963393/0e5b13c6-f920-4e98-9642-175179a93195)

### Card version

v2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: binary_sensor.burze_dzis_net_ostrzezenie_burza
integration: burze_dzis_net
disable_swiper: false

### Integration type

Burze.dzis.net

### Integration configuration

GUI

**Comment by MrBartusek** [comment] 2024-03-24 12:08
Which version of integration are you using?

**Comment by senderbell** [comment] 2024-03-24 12:18
Newest. 2.0.1

**Comment by MrBartusek** [comment] 2024-03-24 12:31
Duplicate of: https://github.com/MrBartusek/MeteoalarmCard/issues/201

**Closed by MrBartusek** 2024-03-24 12:31 UTC
Labels: bug
