### ISSUE TITLE
Error on NWS event type "Special Weather Statement"

### ISSUE THREAD

**Issue by gridlockjoe** [MrBartusek/MeteoalarmCard#209] opened 2023-08-15 00:52 UTC
### Describe the bug

The card is erroring when an event type of "Special Weather Statement" is issued.

I have pasted the integration attributes in the next field.

Perhaps a different color (blue?) could be assigned to purely advisory alerts.

### Integration state attributes

alerts: 
- area: >-
    Houston; Trinity; Madison; Walker; San Jacinto; Polk; Burleson; Brazos;
    Washington; Grimes; Montgomery; Northern Liberty; Colorado; Austin; Waller;
    Inland Harris; Wharton; Fort Bend; Inland Matagorda; Inland Brazoria; Inland
    Galveston; Southern Liberty
  certainty: Observed
  description: |-
    Elevated fire weather conditions will persist into midweek. Dry
    vegetation and fuels are in place from the lack of significant
    rainfall. In addition, low minimum relative humidities in the
    18-35% range are forecast for the next several days which could
    heighten grass and wildfire risks.

    All Southeast Texas counties have burn bans in effect. Avoid outdoor
    burning and double check for any equipment that may produce
    sparks such as chains, bearings, exhaust and other equipment on
    vehicles that could cause sparks. Avoid discarding lit cigarettes
    outside.
  ends: null
  event: Special Weather Statement
  instruction: null
  response: Execute
  sent: '2023-08-14T04:15:00-05:00'
  severity: Moderate
  title: Special Weather Statement issued August 14 at 4:15AM CDT
  urgency: Expected
  NWSheadline: 'null'
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-08-14T04:15:00-05:00'
  expires: '2023-08-16T04:15:00-05:00'
  endsExpires: '2023-08-16T04:15:00-05:00'
  onset: '2023-08-14T04:15:00-05:00'
  status: Actual
  messageType: Alert
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Houston/Galveston TX
  id: urn:oid:2.49.0.1.840.0.efa6389292a99638a3268203b5960ca4e4e024f9.001.1
  zoneid: TXZ213,TXC201
- area: Waller; Inland Harris
  certainty: Likely
  description: |-
    * WHAT...For the Excessive Heat Warning, dangerously hot
    conditions with heat index values up to 113 degrees. For the
    Heat Advisory on Tuesday, heat index values up to 109 degrees expected.

    * WHERE...Waller and Inland Harris Counties.

    * WHEN...For the Excessive Heat Warning, until 9 PM CDT this
    evening. For the Heat Advisory, from 9 PM this evening to 9 PM
    CDT Tuesday.

    * IMPACTS...Extreme heat and humidity will significantly increase
    the potential for heat related illnesses, particularly for those
    working or participating in outdoor activities.
  ends: '2023-08-14T21:00:00-05:00'
  event: Excessive Heat Warning
  instruction: |-
    Drink plenty of fluids, stay in an air-conditioned room, stay out
    of the sun, and check up on relatives and neighbors. Young
    children and pets should never be left unattended in vehicles
    under any circumstances.

    Take extra precautions if you work or spend time outside. When
    possible reschedule strenuous activities to early morning or
    evening. Know the signs and symptoms of heat exhaustion and heat
    stroke. Wear lightweight and loose fitting clothing when
    possible. To reduce risk during outdoor work, the Occupational
    Safety and Health Administration recommends scheduling frequent
    rest breaks in shaded or air conditioned environments. Anyone
    overcome by heat should be moved to a cool and shaded location.
    Heat stroke is an emergency! Call 9 1 1.
  response: Execute
  sent: '2023-08-14T15:29:00-05:00'
  severity: Severe
  title: >-
    Excessive Heat Warning issued August 14 at 3:29PM CDT until August 14 at
    9:00PM CDT
  urgency: Expected
  NWSheadline:
    - >-
      EXCESSIVE HEAT WARNING REMAINS IN EFFECT UNTIL 9 PM CDT THIS EVENING...
      ...HEAT ADVISORY IN EFFECT FROM 9 PM THIS EVENING TO 9 PM CDT TUESDAY
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-08-14T15:29:00-05:00'
  expires: '2023-08-14T23:30:00-05:00'
  endsExpires: '2023-08-14T21:00:00-05:00'
  onset: '2023-08-14T15:29:00-05:00'
  status: Actual
  messageType: Update
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Houston/Galveston TX
  id: urn:oid:2.49.0.1.840.0.971b40e66dc820dc9159a88ba2285faf7dcdfd6a.006.2
  zoneid: TXZ213,TXC201
- area: Waller; Inland Harris
  certainty: Likely
  description: |-
    * WHAT...For the Excessive Heat Warning, dangerously hot
    conditions with heat index values up to 113 degrees. For the
    Heat Advisory on Tuesday, heat index values up to 109 degrees expected.

    * WHERE...Waller and Inland Harris Counties.

    * WHEN...For the Excessive Heat Warning, until 9 PM CDT this
    evening. For the Heat Advisory, from 9 PM this evening to 9 PM
    CDT Tuesday.

    * IMPACTS...Extreme heat and humidity will significantly increase
    the potential for heat related illnesses, particularly for those
    working or participating in outdoor activities.
  ends: '2023-08-15T21:00:00-05:00'
  event: Heat Advisory
  instruction: |-
    Drink plenty of fluids, stay in an air-conditioned room, stay out
    of the sun, and check up on relatives and neighbors. Young
    children and pets should never be left unattended in vehicles
    under any circumstances.

    Take extra precautions if you work or spend time outside. When
    possible reschedule strenuous activities to early morning or
    evening. Know the signs and symptoms of heat exhaustion and heat
    stroke. Wear lightweight and loose fitting clothing when
    possible. To reduce risk during outdoor work, the Occupational
    Safety and Health Administration recommends scheduling frequent
    rest breaks in shaded or air conditioned environments. Anyone
    overcome by heat should be moved to a cool and shaded location.
    Heat stroke is an emergency! Call 9 1 1.
  response: Execute
  sent: '2023-08-14T15:29:00-05:00'
  severity: Moderate
  title: Heat Advisory issued August 14 at 3:29PM CDT until August 15 at 9:00PM CDT
  urgency: Expected
  NWSheadline:
    - >-
      EXCESSIVE HEAT WARNING REMAINS IN EFFECT UNTIL 9 PM CDT THIS EVENING...
      ...HEAT ADVISORY IN EFFECT FROM 9 PM THIS EVENING TO 9 PM CDT TUESDAY
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-08-14T15:29:00-05:00'
  expires: '2023-08-14T23:30:00-05:00'
  endsExpires: '2023-08-15T21:00:00-05:00'
  onset: '2023-08-14T21:00:00-05:00'
  status: Actual
  messageType: Alert
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Houston/Galveston TX
  id: urn:oid:2.49.0.1.840.0.971b40e66dc820dc9159a88ba2285faf7dcdfd6a.006.1
  zoneid: TXZ213,TXC201
- area: >-
    Chambers; Fort Bend; Inland Brazoria; Inland Galveston; Southern Liberty;
    Coastal Harris; Coastal Galveston
  certainty: Likely
  description: |-
    * WHAT...Dangerously hot conditions with heat index values up to
    113 degrees and maximum temperatures up to 105 degrees.

    * WHERE...Chambers, Fort Bend, Inland Brazoria, Inland
    Galveston, Southern Liberty, Coastal Harris and Coastal
    Galveston Counties.

    * WHEN...Until 9 PM CDT Tuesday.

    * IMPACTS...Extreme heat and humidity will significantly
    increase the potential for heat related illnesses,
    particularly for those working or participating in outdoor
    activities.
  ends: '2023-08-15T21:00:00-05:00'
  event: Excessive Heat Warning
  instruction: |-
    Drink plenty of fluids, stay in an air-conditioned room, stay out
    of the sun, and check up on relatives and neighbors. Young
    children and pets should never be left unattended in vehicles
    under any circumstances.

    Take extra precautions if you work or spend time outside. When
    possible reschedule strenuous activities to early morning or
    evening. Know the signs and symptoms of heat exhaustion and heat
    stroke. Wear lightweight and loose fitting clothing when
    possible. To reduce risk during outdoor work, the Occupational
    Safety and Health Administration recommends scheduling frequent
    rest breaks in shaded or air conditioned environments. Anyone
    overcome by heat should be moved to a cool and shaded location.
    Heat stroke is an emergency! Call 9 1 1.
  response: Execute
  sent: '2023-08-14T15:29:00-05:00'
  severity: Severe
  title: >-
    Excessive Heat Warning issued August 14 at 3:29PM CDT until August 15 at
    9:00PM CDT
  urgency: Expected
  NWSheadline:
    - EXCESSIVE HEAT WARNING NOW IN EFFECT UNTIL 9 PM CDT TUESDAY
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-08-14T15:29:00-05:00'
  expires: '2023-08-14T23:30:00-05:00'
  endsExpires: '2023-08-15T21:00:00-05:00'
  onset: '2023-08-14T15:29:00-05:00'
  status: Actual
  messageType: Update
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Houston/Galveston TX
  id: urn:oid:2.49.0.1.840.0.971b40e66dc820dc9159a88ba2285faf7dcdfd6a.003.1
  zoneid: TXZ213,TXC201
- area: >-
    Inland Harris; Inland Brazoria; Inland Galveston; Coastal Harris; Coastal
    Brazoria; Coastal Galveston; Brazoria Islands; Galveston Island; Bolivar
    Peninsula
  certainty: Unknown
  description: |-
    The Texas Commission on Environmental Quality (TCEQ) has issued an
    Ozone Action Day for the Houston, Galveston, and Brazoria area for Tuesday,
    August 15, 2023.

    Atmospheric conditions are expected to be favorable for producing
    high levels of ozone pollution in the Houston, Galveston, and
    surrounding areas on Tuesday. You can help prevent ozone pollution by
    sharing a ride, walking, riding a bicycle, taking your lunch to work,
    avoiding drive through lanes, conserving energy and keeping your vehicle
    proper tuned.

    For more information on ozone:
    Ozone: The Facts www.tceq.texas.gov/airquality/monops/ozonefacts.html
    EPA AirNow: www.airnow.gov/?city=Houston&state=TX&country=USA
    Take Care of Texas:
    www.takecareoftexas.org/conservation-tips/keep-our-air-clean
  ends: null
  event: Air Quality Alert
  instruction: null
  response: Monitor
  sent: '2023-08-14T13:59:00-05:00'
  severity: Unknown
  title: Air Quality Alert issued August 14 at 1:59PM CDT
  urgency: Unknown
  NWSheadline:
    - Ozone Action Day
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-08-14T13:59:00-05:00'
  expires: '2023-08-15T18:00:00-05:00'
  endsExpires: '2023-08-15T18:00:00-05:00'
  onset: '2023-08-14T13:59:00-05:00'
  status: Actual
  messageType: Alert
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Houston/Galveston TX
  id: urn:oid:2.49.0.1.840.0.7cea0c93cd8645c49085fc96a03dbaadc96689e1.001.1
  zoneid: TXZ213,TXC201

integration: weatheralerts
state: TX
zone: TXZ213,TXC201
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Inland Harris

### Screenshots

![SWS](https://github.com/MrBartusek/MeteoalarmCard/assets/66843924/b4252494-fea1-4bfe-94b4-a3ce125b6260)

### Card version

v2.5.3

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: sensor.inland_harris
integration: weatheralerts
hide_when_no_warning: false
override_headline: false
theme: LCARS Kronos
card_mod:
  class: middle-contained

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

sensor:
  - platform: weatheralerts
    state: TX
    zone: 213
    county: 201

**Comment by MrBartusek** [comment] 2023-08-15 09:25
Duplicate of #286

**Closed** 2023-08-15 09:25 UTC
Labels: bug, duplicate
