### ISSUE TITLE
DWD entities not compatible with dwd integration setting. German language

### ISSUE THREAD

**Issue by Tobboss** [MrBartusek/MeteoalarmCard#226] opened 2023-10-16 13:33 UTC
### Describe the bug

Just installed Meteoalarm to use it with the HA core DWD integration for weather alarms. The entities are not compatible to the chosen integration. My HA is in German. Both entities are rejected solo and together.
Using HA Core 2023.10.2 and the official core integration for dwd weather alarms.

### Integration state attributes

region_name: Stadt Langenfeld (Rhld.)
region_id: 805158020
last_update: 2023-10-16T13:23:38.799000+00:00
warning_count: 0
attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings 805158020 Aktuelle Warnstufe

### Screenshots

![Error message and config](https://github.com/MrBartusek/MeteoalarmCard/assets/4268049/4f23261d-0dc5-4f30-82d9-f5535f1c76c6)

### Card version

v2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: sensor.dwd_weather_warnings_805158020_aktuelle_warnstufe
  - entity: sensor.dwd_weather_warnings_805158020_vorwarnstufe
integration: dwd
hide_when_no_warning: false

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI

**Comment by MrBartusek** [comment] 2023-10-16 13:43
Duplicate of: #214

**Closed** 2023-10-16 13:43 UTC
Labels: bug, duplicate
