### ISSUE TITLE
Card empty when wind meteo alert

### ISSUE THREAD

**Issue by Gunth** [MrBartusek/MeteoalarmCard#17] opened 2021-05-20 11:24 UTC
**Describe the bug**
Yesterday i had a strom alert and was correctly displayed, this morning a upgrade the card to 1.5.0 ( dont know if it is related ) and one hour after i had a new wind alert but now the card is empty.

![image](https://user-images.githubusercontent.com/1955976/118969496-6874f000-b96d-11eb-972e-4841105fa335.png)

No javascript error in the chrome console.

If it can help here is the link to the alert : http://meteoalarm.eu/fr_FR/1/0/BE005-Belgique.html

Here is my binary_sensor.meteoalarm entity description :

```
language: fr-FR
category: Met
event: Jaune Vent Avertissement
responseType: Prepare
urgency: Immediate
severity: Moderate
certainty: Likely
effective: 2021-05-21T10:00:00+00:00
onset: 2021-05-21T10:00:00+00:00
expires: 2021-05-21T19:59:59+00:00
senderName: Royal Meteorological Institute of Belgium
headline: Jaune Vent Avertissement pour Belgique - Hainaut / Henegouwen
description: Demain vendredi, le vent se renforcera. Nous attendons un vent assez fort avec des rafales jusqu'a 70 ou 80 km/h dans l'interieur des terres et un vent fort a tres fort avec des rafales jusqu'a 90 km/h au littoral.
instruction: Quelques branches ou arbres cassés.
Difficultés de circulation localisées, surtout pour des véhicules à fortes prise au vent.
Conduisez avec précautions sur les routes exposées et faites attentions aux objets emportés par le vent.
web: http://meteoalarm.eu/fr_FR/0/0/BE005.html
awareness_level: 2; yellow; Moderate
awareness_type: 1; Wind
attribution: Information provided by MeteoAlarm
friendly_name: Meteo alarm
device_class: safety
```

**To Reproduce**
No realy steps to reproduce, just configure it

**Expected behavior**
Card need to display the orange wind alert

**Screenshots**
![image](https://user-images.githubusercontent.com/1955976/118970413-7f681200-b96e-11eb-87e4-ccef91dc5389.png)

**System (please complete the following information):**
 - Card version: 1.1.5
 - Integration type: Core (https://www.home-assistant.io/integrations/meteoalarm/)
![image](https://user-images.githubusercontent.com/1955976/118970194-3e6ffd80-b96e-11eb-9cb5-838bc827f6a1.png)

 - Installation type: HACS

**Comment by MrBartusek** [comment] 2021-05-20 11:44
Yes, I can confirm that the bug was introduced in v1.5.0. I will release a fix for it as soon as possible

**Comment by MrBartusek** [comment] 2021-05-20 12:54
Fixed in 1.5.1

**Closed by MrBartusek** 2021-05-20 12:54 UTC
Labels: bug

**Comment by Gunth** [comment] 2021-05-20 13:09
Working again, Thanks ! :-)

**Comment by dddesign** [comment] 2021-06-21 19:28
I have the same issue: no card if there is a warning.
the problem has to do with the station (https://www.meteoalarm.eu/de_GE/0/0/CH143-Thalwil-Wetzikon.html) because with an other station (eg. https://www.meteoalarm.eu/de_GE/0/0/AT005-Salzburg.html) it's working.

meteo alarmcard v1.8.1
ha core v2021.4.3
os 5.13

any hints?

**Comment by MrBartusek** [comment] 2021-06-21 20:16
Hey @dddesign

Could you pleade [open an issue](https://github.com/MrBartusek/MeteoalarmCard/issues/new?assignees=&labels=bug&template=bug_report.md&title=) that will make resolving it easier
