### ISSUE TITLE
Better wording for the English warning messages

### ISSUE THREAD

**Issue by bioxz** [MrBartusek/MeteoalarmCard#62] opened 2021-12-04 23:06 UTC
I noticed that the English warning messages might end up with unfortunate wording. The proposal here would be to find better way for the message structure to avoid this, for example like in the German version (e.g. "Yellow warning: snow/ice").

![Screenshot](https://user-images.githubusercontent.com/1084262/144727078-10534ff3-bcb6-4416-a6da-686ec7691cd5.png)

This would just be a small change in the translation file, but maybe it isn't seen as necessary, thus I'm just posting this as a feature request for now.

**Comment by MrBartusek** [comment] 2021-12-04 23:39
Duplicate of #15

**Closed by MrBartusek** 2021-12-04 23:39 UTC
Labels: duplicate, enhancement

**Comment by MrBartusek** [comment] 2021-12-04 23:45
And as said in other PRs and issues, I really don't like the formating warnings as `Yellow warning: snow/ice` and it's the case in German because the translator just decided it's the only way https://github.com/MrBartusek/MeteoalarmCard/pull/60#discussion_r752282672
